# Generated by Django 4.2.7 on 2023-11-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='diplomas/'),
        ),
        migrations.AddField(
            model_name='experience',
            name='reference_letter',
            field=models.FileField(blank=True, null=True, upload_to='references/'),
        ),
    ]
