# Generated by Django 3.2.8 on 2023-12-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0003_alter_testimonial_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials'),
        ),
    ]
