# Generated by Django 3.2.8 on 2023-12-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0004_alter_testimonial_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='references',
            field=models.FileField(default='default_reference.pdf', upload_to='references/'),
        ),
    ]
