# Generated by Django 3.2.8 on 2023-12-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0005_testimonial_references'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='references',
            new_name='references_file',
        ),
    ]
